version: '2.3'
services:
    jupyter_notebook:
        build: ./deep_learning/
        runtime: nvidia
        ports:
          - "8888:8888"
          - "5000:5000"
          - "1080:1080"
        expose:
            - "8888"
            - "27017"
            - "80"
            - "6379"
            - "8080"
            - "5000"
            - "1080"
        volumes:
            - /home/alex/:/home/user/
            - /tmp/.X11-unix:/tmp/.X11-unix
            #xhost +local:docker in terminal before using
        networks:
          application-network:
              aliases:
              - jupyter.compose
        restart: on-failure
        environment:
        - PYTHONUNBUFFERED=0
        - DISPLAY=unix:1
        command : "jupyter notebook --no-browser --allow-root --ip=0.0.0.0 --port=8888"
        #command : "python3 ./eu_workspace/eu-ai-api/app.py"
networks:
    application-network:
        external: false